theme = "edge"

[editor]
line-number = "relative"
mouse = false
middle-click-paste = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false
