#!/bin/sh -e

printf 'script started' | systemd-cat -t check-battery #write to log when script is called
BATTINFO=`acpi -b | head -n 1`
if [[ `echo $BATTINFO | grep Discharging` && `echo $BATTINFO | cut -f 4 -d " " | tr -d '%,'` < 25 ]] ; then
        printf 'condition is true' | systemd-cat -t check-battery #write to log if condition is true
        DISPLAY=:0 /usr/bin/notify-send -u critical -t 6000 "Low battery" "$BATTINFO"
fi
if [[ `echo $BATTINFO | grep Charging` && `echo $BATTINFO | cut -f 4 -d " " | tr -d '%,'` > 80 ]] ; then
        printf 'condition is true' | systemd-cat -t check-battery #write to log if condition is true
        DISPLAY=:0 /usr/bin/notify-send -u normal -t 6000 "Battery is adequately charged" "$BATTINFO"
fi
