#!/bin/sh -e

# set -e
# fusermount -uz /home/phoenix/Depot || true

# killall -q rclone

# Wait until the processes have been shut down
# while pgrep -u $UID -x rclone >/dev/null; do sleep 1; done

# echo -n "done" 

rclone mount depot: /home/phoenix/Depot/ &
